### ISSUE TITLE
deprecation reason

### ISSUE THREAD

**Issue by rubydesign** [tanmaykm/JudyDicts.jl#2]
Hi,

could you elaborate on why this is deprecated. 
Or what that even means / what context 

Thanks

btw, i had done this wrapping for ruby once and found that to get good comparison, you need _really_ big arrays and test random and sequential access. 
i mean i don't know what conclusions you took from the existing tests?

**Comment by tanmaykm** [comment]
Hi @dancinglightning, the reason for deprecation is as mentioned here: https://github.com/tanmaykm/JudyDicts.jl/commit/04e17ad42792868f2151e31831b49f8f2b9dc0dd#commitcomment-12870144

It was indeed faster in some cases (results here: https://github.com/tanmaykm/JudyDicts.jl) when used suitably.

It's possible to revive this if needed. Please feel free to submit a PR.

**Comment by rubydesign** [comment]
Ok, makes sense.
Maybe worth putting in the readme.

If you revieve it, i would make some tests for SparseMatrix usage, 
especially multiplacation.
I do believe that there is factors to be gained.
At your leasure, but let me know if you do.
T.

Tanmay Mohapatra wrote:
